name: ServiceB Master
on:
  push:
    branches:
      - main
    paths:
      - 'serviceB/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: docker
      volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - run: docker ps -a
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls -la
      - run: echo "🍏 This job's status is ${{ job.status }}."
  integration-test1:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: cache out directory
        uses: actions/cache@v2
        env:
          cache-name: integration-test1
        with:
          path: out/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref }}
  integration-test2:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: cache out directory
        uses: actions/cache@v2
        env:
          cache-name: integration-test2
        with:
          path: out/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref }}
      - run: make integration-test2
  integration-test3:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - run: false
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - run: echo "I'm deployed"

