name: Deploy

on:
  workflow_run:
    workflows: ["ServiceB Master"]
    branches: [main]
    types: [completed]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "I'm deployed"
